1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

In [1]:
print("python check")

python check


In [2]:
import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("After replacing NaN:")
print(arr)

# Interchange rows and columns (Transpose)
result = arr.T

print("\nAfter interchanging rows and columns:")
print(result)

After replacing NaN:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After interchanging rows and columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


2) Move axes of 3D array to new positions

In [3]:
import numpy as np

arr = np.arange(24).reshape(2,3,4)

print("Original Shape:", arr.shape)

# Move axis 0 to axis 2
new_arr = np.moveaxis(arr, 0, 2)

print("New Shape:", new_arr.shape)
print(new_arr)

Original Shape: (2, 3, 4)
New Shape: (3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


3) Replace NaN values with average of columns

In [4]:
import numpy as np

arr = np.array([[1, np.nan, 3],
                [4, 5, np.nan],
                [7, 8, 9]])

print("Original Array:")
print(arr)

# Column averages ignoring NaN
col_mean = np.nanmean(arr, axis=0)

# Find NaN positions
inds = np.where(np.isnan(arr))

# Replace NaN with column mean
arr[inds] = np.take(col_mean, inds[1])

print("\nAfter Replacing NaN:")
print(arr)

Original Array:
[[ 1. nan  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]]

After Replacing NaN:
[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


4) Replace negative value with zero in numpy array using replace

In [5]:
import numpy as np

arr = np.array([5, -3, 7, -2, 8, -9])

arr[arr < 0] = 0

print(arr)

[5 0 7 0 8 0]
