In [1]:
print("connected")

connected


1) Create numpy array and perform following operation > Convert 1D array to 2D > Print Array Attributes(Like shape, dimenssion, data type, itemsize) > Create a 3×3 NumPy array of all 9 > Create a 1D array of 10 evenly spaced values between 25 and 125 > Convert a Python list into a NumPy array > Reverse a 1D NumPy array > Create a 4×4×3 array and extract value at its second set, first row and last column > Create a 4×4 and Extract Odd Rows and Even Columns > Slice the first two rows and first two columns of econd set from a 4×4×3 array > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] > Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element. > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]

In [2]:
import numpy as np

# 1) Create NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original 1D Array:")
print(arr)

# Convert 1D array to 2D
arr_2d = arr.reshape(2, 3)
print("\n1D to 2D Array:")
print(arr_2d)

# Print array attributes
print("\nArray Attributes:")
print("Shape:", arr_2d.shape)
print("Dimension:", arr_2d.ndim)
print("Data Type:", arr_2d.dtype)
print("Item Size:", arr_2d.itemsize)

# Create 3x3 NumPy array of all 9
nine_arr = np.full((3, 3), 9)
print("\n3x3 Array of all 9:")
print(nine_arr)

# Create 1D array of 10 evenly spaced values between 25 and 125
space_arr = np.linspace(25, 125, 10)
print("\n10 evenly spaced values between 25 and 125:")
print(space_arr)

# Convert Python list into NumPy array
my_list = [10, 20, 30, 40, 50]
list_arr = np.array(my_list)
print("\nPython List to NumPy Array:")
print(list_arr)

# Reverse a 1D NumPy array
reverse_arr = list_arr[::-1]
print("\nReversed 1D Array:")
print(reverse_arr)

# Create a 4x4x3 array and extract value at second set, first row, last column
arr_3d = np.arange(48).reshape(4, 4, 3)
print("\n4x4x3 Array:")
print(arr_3d)

value = arr_3d[1, 0, -1]
print("\nValue at second set, first row, last column:")
print(value)

# Create a 4x4 array and extract odd rows and even columns
arr_4x4 = np.arange(1, 17).reshape(4, 4)
print("\n4x4 Array:")
print(arr_4x4)

odd_rows_even_cols = arr_4x4[::2, 1::2]
print("\nOdd Rows and Even Columns:")
print(odd_rows_even_cols)

# Slice first two rows and first two columns of second set from 4x4x3 array
slice_second_set = arr_3d[1, :2, :2]
print("\nFirst two rows and first two columns of second set:")
print(slice_second_set)

# Replace all odd numbers with -1 by iterating using for loop
arr_odd = np.array([[23, 56, 78, 93],
                    [71, 82, 13, 24]])

print("\nOriginal Array:")
print(arr_odd)

for i in range(arr_odd.shape[0]):
    for j in range(arr_odd.shape[1]):
        if arr_odd[i][j] % 2 != 0:
            arr_odd[i][j] = -1

print("\nAfter replacing odd numbers with -1:")
print(arr_odd)

# Get indices of non-zero elements
arr_nonzero = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr_nonzero)

print("\nIndices of non-zero elements:")
print(indices)

# Arithmetic operations on two arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

addition = a + b
multiplication = a * b

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Multiplication:")
print(multiplication)

# Dot product
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)

print("\nDot Product:")
print(dot_product)

Original 1D Array:
[1 2 3 4 5 6]

1D to 2D Array:
[[1 2 3]
 [4 5 6]]

Array Attributes:
Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8

3x3 Array of all 9:
[[9 9 9]
 [9 9 9]
 [9 9 9]]

10 evenly spaced values between 25 and 125:
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]

Python List to NumPy Array:
[10 20 30 40 50]

Reversed 1D Array:
[50 40 30 20 10]

4x4x3 Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Value at second set, first row, last column:
14

4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]

First two rows and first two columns of second set:
[[12 13]
 [15 16]]

Original Array:
[[23 56 78 93]
 [71 82 13 24]]

After replacing odd numbe