In [2]:
print("connected")

connected


1) Combining a One-Dimensional and a Two-Dimensional NumPy Array

In [3]:
import numpy as np

arr1 = np.array([10, 20, 30])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = np.vstack((arr2, arr1))

print("Combined Array:")
print(result)

Combined Array:
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


2) Flatten a 2D NumPy Array into a 1D Array

In [4]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


3) Reverse a NumPy Array

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

reversed_arr = arr[::-1]

print(reversed_arr)

[50 40 30 20 10]


4) Practice Operations

In [6]:
# a) maximum value

import numpy as np

arr = np.array([10, 50, 20, 80, 30])

print("Maximum:", np.max(arr))

#b) minimum value

import numpy as np

arr = np.array([10, 50, 20, 80, 30])

print("Minimum:", np.min(arr))

# c) number of rows and columns
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

rows, cols = arr.shape

print("Rows:", rows)
print("Columns:", cols)

#d) select element


import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print("All Elements:")
print(arr)

print("Specific Element:")
print(arr[1,2])

#e)  sum of 2D array using for loop

import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

total = 0

for row in arr:
    for value in row:
        total += value

print("Sum =", total)

# f) addition  , substraction , multiplication , diviton

import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)

Maximum: 80
Minimum: 10
Rows: 2
Columns: 3
All Elements:
[[1 2 3]
 [4 5 6]]
Specific Element:
6
Sum = 21
Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


5) iterate 3D aray


In [7]:
import numpy as np

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

for matrix in arr:
    for row in matrix:
        for element in row:
            print(element)

1
2
3
4
5
6
7
8


6) Average, Mean, Median, Mode of Two NumPy 2D Arrays

In [8]:
import numpy as np
from scipy import stats

arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

arr2 = np.array([
    [7,8,9],
    [10,11,12]
])

combined = np.concatenate((arr1, arr2))

print("Combined Array:")
print(combined)

# Average
average = np.average(combined)

# Mean
mean = np.mean(combined)

# Median
median = np.median(combined)

# Mode
mode = stats.mode(combined, keepdims=True)

print("Average =", average)
print("Mean =", mean)
print("Median =", median)
print("Mode =", mode.mode[0])

Combined Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Average = 6.5
Mean = 6.5
Median = 6.5
Mode = [1 2 3]
